### PR TITLE
Update api.service.js

### PR DESCRIPTION
**Pull request by colinkelly**
Bringing back initial hotfix for underscore table name issue ;)

### CODE REVIEW

**Comment by srd2010** [comment]
desperately needed, since it was kicked out in the latest dev-develop branch.
We had to add the line to the compiled scripts to get it back working.

**Comment by colinkelly** [comment]
Can we please merge my pull request? @weierophinney  @ezimuel  Thanks!

**Comment by philgin** [comment]
also awaiting for this fix. Thanks ;)

**Comment by saadhre** [comment]
Merge please :)

**Comment by colinkelly** [comment]
Much happy!!! Such progress ;) Thanks

**Pull request merged**
