### PR TITLE
Normalize API module names for outgoing requests

### PR DESCRIPTION
**Pull request by gsomoza**
This pull request allows special characters inside Api module names by url-encoding the Api name before sending it out as part of a URL parameter. See zfcampus/zf-apigility-documentation#16 for more info.

Specifically, it is designed to allow the backslash character (\) to be present, which is a prerequisite for supporting namespaced Api names (e.g. "Acme\Account") in the Apigility admin. Without this, the UI would insert "Acme\Account" directly as part of the URL for requests to get info from that api. This would cause issues because:
* The backslash character is not a valid character in URL's (see [RFC1738](http://www.faqs.org/rfcs/rfc1738.html))
* And therefore some browsers (like Chrome) convert it to a forward slash, causing a route mismatch when querying the Admin endpoint for that API.

The Apigility Admin API project tried to solve this by converting backslashes into periods. However that may change in the future. This PR doesn't care about that: it will just url-encode whatever the Admin API reports as the Api name before sending it as part of a URL, while still showing it correctly in the user-facing UI elements.

Specific changes this PR introduces:
* Requests to the admin API will be used with the url-encoded version of the Api name. So if its "Acme\Account" the requested URL will use "Acme%5CAccount" instead.
* The above will also be true for the routes (AngularUI Router states) in the address bar.
* The user-facing UI elements will correctly show the backslash.

It would seem to me that all of the changes are backwards-compatible, but it would probably be a good idea to get that reviewed JIC.

### CODE REVIEW

**Comment by gabrielsomoza** [comment]
Note: a couple more commits still pending (e.g. tests right now don't pass), just wanted to see if this is interesting enough to merge. Its also part of other PRs I'll hopefully be making across some of the Apigility projects in order to provide proper support for namespaced API names, so I'll reference those other PRs as well to provide a better picture of how everything could make sense as a whole.

**Comment by gabrielsomoza** [comment]
Ok, couldn't fix tests and actually realised the issue with that is also happening on `master` with me as well. I suspect it might be related to the fact that with me bower can't resolve which version of Angular to use, so I manually opted for version `1.4.8` - but this might be material for a different ticket.

**Comment by gabrielsomoza** [comment]
Updated the commit to take a more transparent approach (all changes were moved to `api.service.js`)

**Comment by kevinpapst** [comment]
I would have named the variable moduleName instead of moduleParam ;-) but beside that, I like this PR. 

The expected "Module Naming convention" is very strict and tends to cause troubles with the Admin UI if you edit the module config manually. 
The whole idea behind these combined PRs would give us more freedom in 
a) structuring and naming of Modules and Namespaces
b) switching back and forth between using the Admin UI and editing the config files directly

**Comment by gabrielsomoza** [comment]
Haha funny: I was also considering `moduleName` (its indeed the most natural choice), but settled for `moduleParam` cause it also reflects the fact that its being used as a param - e.g. `urlEncodedModuleName` would have that same effect (but then: its way too long for my taste). But honestly I'm not against changing back to moduleName if that's better for everyone else.

Anyway, thanks for reviewing this PR! I had precisely those issues you mentioned about editing the module config manually :)

**Comment by weierophinney** [comment]
Merged to develop for release with 1.3.0; thanks, @gsomoza !

**Pull request closed without merging**
