### PR TITLE
Fixed the new DB connected + new API error

### PR DESCRIPTION
**Pull request by ezimuel**
This PR fixes the issue #74 and improve the error detail on new API in case of existing module.

### CODE REVIEW

**Comment by ezimuel** [comment]
@guliano Thanks for notice that! I just removed it.

**Comment by blackhack123** [comment]
i have the same error on try to created db conect 
and i try with this 
"zfcampus/zf-apigility-admin-ui": "dev-master"
but not work my services the same error

captura

**Comment by ezimuel** [comment]
@blackhack123 did you try to use also "zfcampus/zf-apigility-admin": "dev-master" ?

**Comment by blackhack123** [comment]
hi yeah i try with these but have the same problem

Date: Thu, 24 Dec 2015 00:27:26 -0800

**Comment by michelcandido** [comment]
Hello, I did have the same problem, I solved used older version "zfcampus/zf-apigility-admin": "1.2"

**Pull request closed without merging**
