### PR TITLE
Responsive display

### PR DESCRIPTION
**Pull request by weierophinney**
This patch is intended for grouping a number of UI responsiveness issues.

- [X] Version string wrapping in header
- [X] Navigation sizing issues at mid-ranges
- [X] Search bar/button grouping
- [X] Dashboard hero image overlap with text
- [X] Navigation visibility in mobile
- [x] Sidebar visibility in mobile
- [x] Navigation toggle should expand on click when in collapsed mode

### CODE REVIEW

**Comment by weierophinney** [comment]
@ezimuel You can track progress as I work on this via the checkboxes. I may add more items as I explore the UI in more detail.

**Comment by weierophinney** [comment]
@ezimuel I've got a ton of issues resolved now. The last two, however, are big: the collapse toggle is not making the navigation menu dropdown appear, and at a certain point, the sidebar disappears entirely, and cannot be found. I'll work on those when I can.

**Comment by weierophinney** [comment]
Down to the last item: sidebar visibility when on narrow screens.

**Comment by weierophinney** [comment]
All set!

**Comment by ezimuel** [comment]
@weierophinney the new responsive design looks good, there are only some minor issues:

- the **search field** in the sidebar shows the X button, to reset the search content, over the Search. Moreover the size of the search input text is too long, it's not aligned with the size of the angular-ui-tree (see image below)

- the **menu** at the top of the screen and the size of the **main content** is not 100% width of the window. I think this should be fixed because folks can take advantages of full screen with pages with a lot of contents, like the Fields page for REST/RPC services (see image below)

apigility_screenshot

- for very small window, the **delete service** button is wrong positioned in the **panel-heading** (it's over the div). In general all the buttons in the panel-heading have the same issue (see image below)

apigility_screenshot2

**Comment by weierophinney** [comment]
> the menu at the top of the screen and the size of the main content is not 100% width of the window

I had to make this change due to problems when resizing the window. Essentially, when we had the content justified, elements would move to a line below, making the header larger and obscuring content in the sidebar and content area. Additionally, it meant it was really hard to calculate exactly when the menu button should appear, as justified == taking entire width. It was far simpler to achieve this by removing the justification.

> the search field in the sidebar shows the X button, to reset the search content, over the Search. Moreover the size of the search input text is too long, it's not aligned with the size of the angular-ui-tree (see image below)

Now fixed!

> for very small window, the delete service button is wrong positioned in the panel-heading

Also fixed! Note: if you size really, really small, it's still a slight issue if the button and text cannot fit in the same line. However, I tried on a variety of sizes down to original iPhone resolution, and it's working correctly in each.

**Comment by weierophinney** [comment]
Finally got the sidebar behavior I want: the toggle now appears in the header, on the left, and toggles between left and right chevrons. This is ready to merge. :)

**Pull request merged**
